
#include "Fraction.h"
//#define DEBUG


using namespace std;

int main()

{
	SetConsoleCP(1251);
	SetConsoleOutputCP(1251);

	//Fraction *n;
	//Fraction *a;
	//Fraction* b;
	long numb;
	long nom1, nom2, den1, den2;
	cout << "Введите числитель и знаменатель первой дроби:";
	cin >> nom1 >> den1;
	cout << "Введите числитель и знаменатель второй дроби:";
	cin >> nom2 >> den2;

	cout << "Введите число:";
	cin >> numb;


	try
	{
		shared_ptr<Fraction>n(new Fraction());
		cout << "Checking default constructor..." << endl;
		cout << *n;
		
	}

	catch (Fraction_exception & ex)
	{
		cout << ex.what() << endl;
#ifdef DEBUG
		return 1;
#endif // DEBUG
		
	}
	catch (...)
	{
		cout << "Вызвано системное исключение" << endl;


	}
	
	
	try
	{
		shared_ptr<Fraction>a(new Fraction(nom1, den1));
		shared_ptr<Fraction>b(new Fraction(nom2, den2));

			

		cout << (*a);

		/*cout << "Сумма дробей: " << *a + *b << endl;

		cout << "Разность дробей: " << *a - *b << endl;


		cout << "Унарный минус: " << -(*a) << endl;

		cout << "Произведение дробей: " << (*a) *(* b) << endl;

		cout << "Частное дробей: " << (*a) /( *b) << endl;
	
	
		cout << "Умножение дроби на число: " << (*a) * numb << endl;

		cout << "Деление дроби на число: " << (*a) / numb << endl;

		cout << "Сложение дроби с числом: " << (*a) + numb << endl;

		cout << "Разность дроби с числом: " << (*a) - numb << endl;

	
		cout << "Разность числа с дробью " << numb - (*a) << endl;


		cout << "Сумма числа с дробью " << numb + (*a) << endl;


		cout << "Деление числа на дробь " << numb / (*a) << endl;


		cout << "Умножение числа на дробь " << numb * (*a) << endl;
				
		if (*a > *b)
			cout << "Первая дробь больше \n ";
		if (*a < *b)
			cout << "Первая дробь меньше \n ";
		if (*a == *b)
			cout << "Дроби равны\n";
		if (*a != *b)
			cout << "Дроби не равны\n";
		if (*a >= *b)
			cout << "Первая дробь больше либо равна второй\n";
		if (*a <= *b)
			cout << "Первая дробь меньше либо равна второй\n";

		cout << "Операции приведения типа:" << double(*a) << ";";
		cout << double(*b) << endl;
		*/
	}
	catch (Fraction_exception & ex)
	{
		cout << ex.what() << endl;
#ifdef DEBUG
		return 1;
#endif // DEBUG
	}
	
	/*catch (my_exception_action & ex)
	{
		cout << ex.what() << endl;
	}*/

	catch (...)
	{
		cout << "Вызвано системное исключение" << endl;
	

	}
	system("pause");

	return 0;
}